import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header";
import { Montserrat } from "next/font/google";
import { createClient } from "@/utils/supabase/server";
import Menu from "@/components/menu";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const supabase = createClient();
  const {
    data: { session },
  } = await supabase.auth.getSession();

  const showMenu = Boolean(session);
  return (
    <html lang="en">
      <body className={`${montserrat.className}`}>
        <div className="min-h-screen w-full flex">
          {showMenu && <Menu />}

          <main className={showMenu ? "ml-60 flex-1" : "flex-1"}>
            <Header/>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
